import time

class storyline():
    def __init__(self):
        self.storyline = True 

    def archer():
        print('Your adventure begins now {username}.')
        time.sleep(2)
        print('You look around, confused, you decide to wander around.')
        time.sleep(1)
        print('You search for answers, none to be found.')
        time.sleep(4)
        print('UNTIL......')
        print('You encounter a skeleton, a fierce battle begins.')
        time.sleep(3)
    def shoot():
            time.sleep(1)
            print('You have done 20 damage.')
            time.sleep(2)
            print('Skeleton attacks, dealing 2 damage.')
            time.sleep(2)
            print('Player: 18/20 hp , Skeleton: 10/30 hp')
    def shoot2():
            time.sleep(1)
            print('You have done 20 damage.')
            time.sleep(2)
            print('The skeleton has sadly passed away due to you piercing it with your arrow.')
            time.sleep(2)
            print('Player: 18/20 hp , Skeleton: 0/30 hp')
    def shoot3():
            time.sleep(1)
            print('You have done 0 damage.')
            time.sleep(2)
            print('The skeleton hits you again for 1 damage.')
            time.sleep(2)
            print('Player: 17/20 hp , Skeleton: 10/30 hp')     
    def shoot4():
            time.sleep(1)
            print('No Running')
            time.sleep(2)
            print('The skeleton hits you again for 4 damage.')
            time.sleep(2)
            print('Player: 14/20 hp , Skeleton: 10/30 hp')            
    def defend():
            time.sleep(2)
            print('You have decided to defend, no damage dealt.')
            time.sleep(2)
            print('Skeleton attacks, dealing 1 damage.')
            time.sleep(2)
            print('Player: 19/20 hp, Skeleton: 30 hp')
    def defend2():
            time.sleep(2)
            print('You have chosen to shoot.')
            time.sleep(2)
            print('You have dealt 20 damage.')
            time.sleep(2)
            print('Skeleton attacks, dealing 2 damage.')
            time.sleep(2)
            print('Player: 17/20 hp, Skeleton: 10 hp')
    def defend3():
            time.sleep(2)
            print('You have chosen to Defend again for some reason.')
            time.sleep(2)
            print('You have dealt 0 damage.')
            time.sleep(2)
            print('Skeleton attacks, dealing 1 damage.')
            time.sleep(2)
            print('Player: 18/20 hp, Skeleton: 10 hp')
    def defend4():
            time.sleep(2)
            print('You have chosen to Run.')
            time.sleep(2)
            print('After defending is insane.')
            time.sleep(2)
            print('Why coward out of a fight?')
            time.sleep(2)
            print("I'm taking away your privilege to run.")
    def run():
            print('WRONG CHOICE, YOU ARE NOT ALLOWED TO RUN!!!!')
            time.sleep(3)
            print('You have taken 3 damage.')
            time.sleep(2)
            print('Skeleton attacks, dealing 2 damage.')
            time.sleep(2)
            print('Player: 15/20, Skeleton: 30 hp')
            time.sleep(1)
    def run2():
            time.sleep(1)
            print('You have done 20 damage.')
            time.sleep(2)
            print('Skeleton attacks, dealing 2 damage.')
            time.sleep(2)
            print('Player: 18/20 hp , Skeleton: 10/30 hp')
    def run3():
            time.sleep(2)
            print('You have chosen to Defend again for some reason.')
            time.sleep(2)
            print('You have dealt 0 damage.')
            time.sleep(2)
            print('Skeleton attacks, dealing 1 damage.')
            time.sleep(2)
            print('Player: 18/20 hp, Skeleton: 10/30 hp')
    def run4():
            time.sleep(2)
            print('You have chosen to Run.')
            time.sleep(2)
            print("Someone didn't learn their lesson")
            time.sleep(2)
            print('Why coward out of a fight?')
            time.sleep(2)
            print("I'm taking away your privilege to run.")
            time.sleep(2)
            print('You have taken 5 damage')
            time.sleep(3)
            print('Skeleton decides to take pity due to your stupidity')
            time.sleep(2)
            print('Player 10/20, Skeleton: 10/30 hp')
    def run5():
           